## README
Last updated on `r date()` by Sarah Huang

***

### Project requirement

***

The purpose of this project is to demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. You will be graded by your peers on a series of yes/no questions related to the project. You will be required to submit: 


1) a tidy data set as described below
2) a link to a Github repository with your script for performing the analysis 
3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. 
4) a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.  

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained: 

<http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones>

Here are the data for the project: 

<https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip> 

You should create one R script called run_analysis.R that does the following. 

1) Merges the training and the test sets to create one data set.
2) Extracts only the measurements on the mean and standard deviation for each measurement. 
3) Uses descriptive activity names to name the activities in the data set
4) Appropriately labels the data set with descriptive variable names. 
5) From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

### Description of analysis files

***

Table 1: Files in <span style="color:blue">~/project</span>

File name | Description
------------- | -------------
 dataset.zip | Original compressed raw dataset
UCI HAR Dataset | This is a folder that contains the uncompressed raw dataset. This folder is automatically created after unzipping the compressed dataset
run_analysis.R | A R-script created to clean the raw data and output a tidy dataset. See the project requirement above. Detailed steps are explained in the script using comments.
tidy_data.txt | Tidy dataset generated by the R-script above
README.md | Decription of the project requirement, use and connection of all relevant files
CodeBook.md, | Description of variables, the data, and any transformations performed to clean up data


Table 2: Files in <span style="color:blue">~/project/UCI HAR Dataset</span>. Only those imported into R objects in run_analysis.R for calculation are listed. Note that files in <span style="color:blue">Inertial Signals</span> folder are NOT required for calculation as instructed by the course CTA.

File name | Description 
--- |--- 
subject_train.txt | Subject identifiers for the training dataset
X_train.txt | Training dataset 
y_train.txt | Activity labels for the training dataset 
subject_test.txt | Subject identifiers for the test dataset 
X_test.txt | Test dataset  
y_test.txt | Activity labels for the test dataset 
features.txt | names of all measured features 
activity_labels.txt | Activity name and label pairs 

### How are the analysis files used to create a tidy dataset

***

1) Download <span style="color:blue">dataset.zip</span> from the link provided
2) Unzip <span style="color:blue">dataset.zip</span> and a folder named <span style="color:blue">UCI HAR Dataset</span> will be automatically created. In this folder, you will find the following 6 files that contain all the data we need to perform the analysis: <span style="color:blue">subject_train.txt</span>, <span style="color:blue">X_train.txt</span>, <span style="color:blue">y_train.txt</span>, <span style="color:blue">subject_test.txt</span>, <span style="color:blue">X_test.txt</span>, <span style="color:blue">y_test.txt</span>. Merge these 6 files to create one dataset
3) Use the information in <span style="color:blue">activity_labels.txt</span> to replace the numeric activity labels with appropriate descriptive activity names in the dataset
4) Use the information in <span style="color:blue">features.txt</span> to label the dataset with descriptive variable names
5) Clean the dataset, generate a tidy dataset and save it to a text file <span style="color:blue">tidy_data.txt</span>
6) All the above is performed by the R-script <span style="color:blue">run_analysis.R</span>
7) The description of analysis files and how these files work with each other is stored in <span style="color:blue">README.md</span> 
8) The description of the data, the variables, and the work performed to trun the messy raw data into tidy data is stored in <span style="color:blue">CodeBook.md</span>

#### *Please see the CodeBook for more information*

***







